Feat/adding fake backend
Codeminer42/intellimize-study-group pull request #8
Opened 2022-10-31 20:11 UTC by Isaac-alencar

## What is going on?
This PR create `NextJS` api routes with a json file as database.

FYI: We stopped using `json-server` since we're gonna continue with `Next api routes`. We tried to use only `lowdb`, but with this library we can't do unit tests for our routes, I decided to move on building our own database with a json file. We're removing the following libs:
- json-server

and adding:
- [node-mocks-http](https://www.npmjs.com/package/node-mocks-http)

## How to test
You can execute all the unit tests with `yarn test  fake-backend/__test__/wines.spec.ts`

2022-10-31 20:11 UTC, Isaac-alencar commented
I'll close #4. This will be the final PR

2022-11-01 19:45 UTC, BrunoViveiros commented on idega/fake-backend/inMemoryDb.ts
> +    id: 1,
We have the same structure in [idega/fake-backend/__tests__/helpers/mocks/wine.ts](https://github.com/Codeminer42/intellimize-study-group/pull/8/files#diff-9f2ba81fa8f2a092831ce37b2950c47282926c5b09c4b563a6889b92be39fa0e) . isn't there a way to reutilize this variable in the inMemoryDb ?

2022-11-01 19:45 UTC, BrunoViveiros commented on idega/fake-backend/queries.ts
> +  process.env.NODE_ENV !== 'test' ?? fs.writeFileSync(file, JSON.stringify(data, null, 2));
right now we are not testing this line, should we create a temporary file instead using the inMemory ? 
the file would be created before each test, and deleted after each test.
Or maybe this is fine like that ?

2022-11-01 19:45 UTC, BrunoViveiros commented on idega/src/__tests__/winesRoutes.spec.ts
> +    const newWine = {
we should use the [mocks/wine.ts](https://github.com/Codeminer42/intellimize-study-group/pull/8/files#diff-9f2ba81fa8f2a092831ce37b2950c47282926c5b09c4b563a6889b92be39fa0e) file here

2022-11-01 19:55 UTC, BrunoViveiros commented on idega/fake-backend/queries.ts
> +  process.env.NODE_ENV !== 'test' ?? fs.writeFileSync(file, JSON.stringify(data, null, 2));
@talyssonoc is doing that a good idea? if so would github allow us to use `fs.writeFileSync` on the pipeline ?

2022-11-01 20:00 UTC, Isaac-alencar commented on idega/fake-backend/queries.ts
> +  process.env.NODE_ENV !== 'test' ?? fs.writeFileSync(file, JSON.stringify(data, null, 2));
I think you have a valid point, not sure if `Github` allow us to create a file while we're running the pipeline. Also, I don't think it is worth the effort since we're gonna change to or own back-end in the future

2022-11-03 00:54 UTC, paola-machado approved these changes

2022-11-03 17:58 UTC, Isaius requested changes

2022-11-03 17:58 UTC, Isaius commented on idega/fake-backend/queries.ts
> +export type Wine = {
This was already defined in the [wine context](https://github.com/Codeminer42/intellimize-study-group/blob/main/idega/src/contexts/WineContext.tsx#L3). Shouldn't we use that?

2022-11-03 18:46 UTC, izass requested changes

2022-11-03 18:59 UTC, talyssonoc commented on idega/fake-backend/__tests__/queries.spec.ts
> +      expect.objectContaining<Wine>({} as Wine)
Can we add more details about the expectation for the content of the object?

2022-11-03 18:59 UTC, talyssonoc commented on idega/fake-backend/__tests__/queries.spec.ts
> +      expect.objectContaining<Wine>({} as Wine)
Same here.

2022-11-03 18:59 UTC, talyssonoc commented on idega/fake-backend/__tests__/queries.spec.ts
> +    expect(wines?.id).toBe(1)
We should use strict assertion here:

```suggestion
    expect(wines!.id).toBe(1)
```

2022-11-03 18:59 UTC, talyssonoc commented on idega/fake-backend/__tests__/queries.spec.ts
> +    const newWine = await add(wine());
We should invert these lines to avoid depending on in-memory behavior.

2022-11-03 18:59 UTC, talyssonoc commented on idega/src/__tests__/winesRoutes.spec.ts
> +    expect(res._getJSONData()['data'].length).toBe(1);
```suggestion
    expect(res._getJSONData().data.length).toBe(1);
```

2022-11-03 18:59 UTC, talyssonoc commented on idega/src/pages/api/wines/[id].ts
> +};
```suggestion
type ApiResponse = { data: Wine } | { error: string };
```

2022-11-03 18:59 UTC, talyssonoc commented on idega/src/pages/api/wines/[id].ts
> +    const response = await getById(Number(id));
```suggestion
    const wine = await getById(Number(id));
```

2022-11-03 18:59 UTC, talyssonoc commented on idega/src/pages/api/wines/index.ts
> +      const response = await add(req.body);
```suggestion
      const newWine = await add(req.body);
```

2022-11-03 18:59 UTC, talyssonoc commented on idega/src/pages/api/wines/index.ts
> +      const response = await get();
```suggestion
      const wines = await get();
```

2022-11-08 20:52 UTC, Isaius approved these changes

2022-11-08 22:34 UTC, BrunoViveiros requested changes

2022-11-08 22:34 UTC, BrunoViveiros commented on idega/fake-backend/__tests__/GetWine.useCase.spec.ts
> +  it('returns a new wine', async () => {
I thinks this was supposed to be, `return a given wine`

2022-11-08 22:34 UTC, BrunoViveiros commented on idega/fake-backend/domain/Wines.ts
> +    if (isValidWine(wine)) {
I think the name here is wrong, because like that it "tells" if a wine is valid it throws a error

2022-11-08 22:34 UTC, BrunoViveiros commented on idega/fake-backend/domain/Wines.ts
> +    if (isValidWine(wine)) {
I think this could be `isWineMissingKeys` or just invert the return of the function

2022-11-08 22:34 UTC, BrunoViveiros commented on idega/fake-backend/infra/WineRepository.ts
> +  getNextId: () => (data.wines.length ? Math.max(...data.wines.map((x: Wine.Type) => x.id)) + 1 : 1),
```suggestion
  getNextId: () => (data.wines.length ? Math.max(...data.wines.map((wine: Wine.Type) => wine.id)) + 1 : 1),
```
Just for better understanding of the code

2022-11-08 22:34 UTC, BrunoViveiros commented on idega/src/__tests__/winesRoutes.spec.ts
> +const wineObjectShape = {
Could we use the wine from `mocks/wine.ts` here ? It's missing the ID but we can add it on like this `{...wine, id: 1 }`

2022-11-08 22:34 UTC, BrunoViveiros commented on idega/src/__tests__/winesRoutes.spec.ts
> +const wineObjectShape = {
Ok these are mocks for the server side, so we  could create a `helper/mock` like that on the client side

2022-11-08 22:34 UTC, BrunoViveiros commented on idega/src/__tests__/winesRoutes.spec.ts
> +    const newWine = {
Same mock would be used here

2022-11-09 01:17 UTC, Isaac-alencar commented on idega/fake-backend/__tests__/GetWine.useCase.spec.ts
> +  it('returns a new wine', async () => {
yup, sorry. it was some copy and paste stuff lol

2022-11-09 01:19 UTC, Isaac-alencar commented on idega/src/__tests__/winesRoutes.spec.ts
> +const wineObjectShape = {
I think we already resolved this on a previous discussion

2022-11-09 18:47 UTC, BrunoViveiros approved these changes

2022-11-10 18:13 UTC, talyssonoc commented on idega/src/pages/api/wines/[id].ts
> +    }
We should return a single wine here, not an array

2022-11-10 18:15 UTC, talyssonoc commented on idega/src/pages/api/wines/index.ts
> +      res.status(201).json({ data: [newWine] });
Here as well

2022-11-11 14:15 UTC, merged